FROM openjdk:17-alpine

ARG JAR_FILE=build/libs/Clubber-Internal.jar

COPY ${JAR_FILE} app.jar
ARG PROFILE=prod
ENV PROFILE=${PROFILE}

ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=${PROFILE}","/app.jar"]
