services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - clubber

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SERVER_HTTP_PORT=4000
    container_name: grafana
    ports:
      - "4000:4000"
    #    volumes:
    #      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - clubber

  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml -config.expand-env=true
    networks:
      - clubber