version: '3'

services:
  backend:
    image: ${DOCKER_REPO}
    build: .
    ports:
      - "8080:8080"
    networks:
      - clubber

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/:/etc/nginx/
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - clubber

networks:
  clubber:
