# 빌드 스테이지
FROM nginx:1.24.0 AS builder

# 필수 패키지 설치
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    wget \
    curl \
    build-essential \
    libpcre3-dev \
    zlib1g-dev \
    libmaxminddb-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

# Nginx 소스 코드 다운로드
ARG NGINX_VERSION=1.24.0
WORKDIR /usr/src
RUN wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz && \
    tar -zxvf nginx-${NGINX_VERSION}.tar.gz && \
    rm nginx-${NGINX_VERSION}.tar.gz

# GeoIP2 모듈 다운로드 및 빌드
RUN git clone https://github.com/leev/ngx_http_geoip2_module.git

WORKDIR /usr/src/nginx-${NGINX_VERSION}
RUN ./configure --with-compat --add-dynamic-module=../ngx_http_geoip2_module && \
    make modules

# 최종 실행 스테이지
FROM nginx:1.24.0

# GeoIP2 모듈 복사 (빌드한 파일만 포함)
COPY --from=builder /usr/src/nginx-${NGINX_VERSION}/objs/ngx_http_geoip2_module.so /usr/lib/nginx/modules/

# 불필요한 캐시 제거
RUN rm -rf /var/cache/apt/*