services:
  backend:
    container_name: backend
    image: ssuclubber/clubber-backend-prod
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./logs:/logs
    ports:
      - "8080:8080"
    networks:
      - clubber

  frontend:
    container_name: frontend
    image: ssuclubber/clubber-front-prod
    environment:
      - TZ=Asia/Seoul
    expose:
      - "3000"
    networks:
      - clubber

  nginx:
    container_name: nginx
    image: ssuclubber/clubber-nginx-prod
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./nginx/:/etc/nginx/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - /var/lib/GeoIP/GeoLite2-Country.mmdb:/var/lib/GeoIP/GeoLite2-Country.mmdb
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - backend
      - frontend
    networks:
      - clubber

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    environment:
      - TZ=Asia/Seoul
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot && nginx -s reload; sleep 12h; done;'"
    networks:
      - clubber

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - ./logs:/var/log/spring-boot
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - clubber

networks:
  clubber: