#global:
#  scrape_interval: 15s
#
#scrape_configs:
#  - job_name: prometheus
#    static_configs:
#      - targets: ['localhost:8080']
#    metrics_path: /actuator/prometheus


global:
  scrape_interval: 15s

scrape_configs:
#  - job_name: 'prometheus'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['localhost:9090']
#
#
#  - job_name: 'grafana'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['grafana:3000']

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ '192.168.0.21:8080' ]