Server:
  port: 8080

spring:
  profiles:
    active: dev
  #Mysql setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cfgycwceugma.ap-northeast-2.rds.amazonaws.com:3306/clubber
    username: admin
    password: ${RDS_PASSWORD}

  config:
    import: application-dev.yml

  application:
    name: clubber

