#name: CI-CD Dev
#
#on:
#  push:
#    branches:
#      - dev
#
#jobs:
#  CI-CD:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#
#      - name: make application.yml
#        run: |
#          cd ./src/main/resources
#          touch ./application.yml
#          echo "${{ secrets.YML }}" > ./application.yml
#        shell: bash
#
#      - name: make application-dev.yml
#        run: |
#          cd ./src/main/resources
#          touch ./application-dev.yml
#          echo "${{ secrets.YML_DEV }}" > ./application-dev.yml
#        shell: bash
#
#      - name: Gradle Caching
#        uses: actions/cache@v3
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Build with Gradle
#        run: ./gradlew clean build -x test
#
#      - name: docker build and push
#        run: |
#          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#          docker build -t ${{ secrets.DOCKER_REPO }}/clubber-backend-dev .
#          docker push ${{ secrets.DOCKER_REPO }}/clubber-backend-dev
#
#      - name: Copy docker-compose.yml to EC2
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.HOST_DEV }}
#          username: ubuntu
#          key: ${{ secrets.PRIVATE_KEY_DEV }}
#          source: ./docker-compose.yml
#          target: /home/ubuntu
#
#
#      - name: Deploy to dev
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST_DEV }}
#          username: ubuntu
#          key: ${{ secrets.PRIVATE_KEY_DEV }}
#          script: |
#            cd /home/ubuntu
#            sudo docker rm -f $(docker ps -qa)
#            sudo docker pull ${{ secrets.DOCKER_REPO }}/clubber-backend-dev
#            sudo docker pull ${{ secrets.DOCKER_REPO }}/clubber-front
#            sudo docker-compose up -d
#            sudo docker image prune -f
#
#
#
#
#
#
#
#
#
#
#
